### ISSUE TITLE
Dockerfile enhancement

### ISSUE THREAD

**Issue by hannah98** [pirate/bookmark-archiver#26]
I recently submitted a [pull request](https://github.com/pirate/bookmark-archiver/pull/25) that paved the way for a Dockerfile for this application.  I am opening this enhancement to engage in discussion with you on how to proceed.

I created a [repository](https://github.com/hannah98/bookmark-archiver-docker) for the Dockerfile.  It is already built on Docker hub and works - however it is under my name.  I'm not sure if you want to support automated builds going forward or not.

One other discussion point is that some platforms have trouble running google-chrome in a Docker container.  You can read some lengthy discussion [here](https://github.com/jessfraz/dockerfiles/issues/65).  Running this container (or any container that utilizes Google Chrome) on an Ubuntu host will generate the "Failed to move to new namespace" error.

One solution I was playing with was to use [PhantomJS](http://phantomjs.org/) instead of Google Chrome.  I already have a [Docker container](https://github.com/hannah98/bookmark-archiver-docker/tree/phantomjs)  built for it, but your application currently doesn't support PDF and PNG snapshots with PhantomJS.  Another bonus to using PhantomJS is that the image is 236MB as opposed to 845MB with Google Chrome.

I am going to be playing with my fork of your application to allow the user to choose (via Env variable) to use either PhantomJS or Google Chrome - if I figure something out I will test and submit a pull request.  

This should be enough material for us to chat about - let me know if you have any questions.

**Comment by pirate** [comment]
Firefox is adding headless mode to Linux quite soon, it may be worth exploring adding that as an alternative to Chromium.  I'll do some more research and report back.

It's reasonable that Chrome has troubles inside of Docker, Chrome uses chroots and kernel namespacing for it's own internal sandbox and I'm not sure how well that can be nested inside of Docker's chroots & namespaces.
I definitely want to use a widely used (i.e. Webkit-based) headless browser for the screenshots, since other rendering engines don't provide consistent enough renders of modern webpages.

Personally I don't use docker for tools like this, because of the huge overhead of re-downloading shared tools that I already have running on my machine (e.g. postgres, nginx, redis, chrome), but I can understand that's not the case for everyone.

**Comment by hannah98** [comment]
Oh sure - I didn't do much research on the PhatomJS rendering so that makes sense to use a Webkit-based browser for rendering.  I hadn't even thought about Firefox.  I will work on a container that can support headless Firefox.

**Comment by hannah98** [comment]
Looking some more, I don't see an obvious way to take a PDF capture of a page using Firefox - that would put Chrome at an advantage to FF for your application.

**Comment by pirate** [comment]
I haven't heard of anyone else running this in a Docker container.  I think it's reasonable to expect most people will install it directly, since the few dependencies it does have would be better off shared with the system and not locked away in a container.

If you do manage to get Chrome working in Docker eventually, comment back and I'd be happy to re-open this.

**Comment by Strubbl** [comment]
I just created another Dockerfile by myself, because i did not see any in this repo. Unfortunately i ran into this issue here.

**Comment by pirate** [comment]
Try basing your image on https://github.com/justinribeiro/dockerfiles/tree/master/chrome-headless @Strubbl

**Comment by pirate** [comment]
See https://github.com/pirate/bookmark-archiver/issues/62 for the active ticket
