### ISSUE TITLE
Add Support for Site Logins

### ISSUE THREAD

**Issue by marlowe310** [pirate/bookmark-archiver#31]
I'm trying to archive a few bookmarks that require I be logged in to the site itself for content to be visible -- which means BA is just outputting a page with the content concealed at this time.

Is there a way to log the chromium instance BA is using in, to prevent that from happening? Thanks much, very impressive work.

**Comment by pirate** [comment]
Have you tried logging in to the sites using chrome normally before running the script?  Headless chrome is just a command line interface to normal Chrome, so it uses all the same cookies.  Any sessions you log into via normal chrome should carry over in headless mode...

If that doesn't work, there is another way but it's quite difficult.  You run headless chrome with the remote debugging port open, then send custom JS commands (which depend on the structure of the site) to issue a POST request which logs you in.  It's quite tricky to do, because you'd have to run the commands within the initial time window before chrome takes the screenshot.

**Comment by pirate** [comment]
Closing this for now, but comment back if you're still having trouble and I'd be happy to re-open this and help out!

**Comment by pirate** [comment]
I stand corrected, apparently `chrome --headless` runs in incognito mode: https://bugs.chromium.org/p/chromium/issues/detail?id=617931

**Comment by pirate** [comment]
Done! https://github.com/pirate/bookmark-archiver/releases/tag/v0.0.3
