### ISSUE TITLE
Link Parsing: Add support for browser history SQLite database

### ISSUE THREAD

**Issue by pirate** [pirate/bookmark-archiver#54]
This will allow people to run BA as an archiver for **all** their browsing history, not just bookmarked pages.

h/t to @FiloSottile for the suggestion

**Comment by pirate** [comment]
Turns out it's really easy:

```bash
cp "$1" .chrome_history.db.tmp
sqlite3 .chrome_history.db.tmp "SELECT \"[\" || group_concat(json_object('timestamp', last_visit_time, 'description', title, 'href', url)) || \"]\" FROM urls;" > downloads/chrome_history.json
rm .chrome_history.db.tmp

./archive downloads/chrome_history.json
```

**Comment by pirate** [comment]
This is done. On master you can now run:

```bash
./bin/export-browser-history --chrome
./archive output/sources/chrome_history.json
# OR
./bin/export-browser-history --firefox
./archive output/sources/firefox_history.json
```

**Comment by GlassedSilver** [comment]
So since I run this in a docker on my server that is running Linux (unRAID to be precise) and my desktop being Windows what I have is a places.sqlite file in my Windows Firefox's profile folder.

I know that I can rsync it to my server, but how would I pass the sqlite file to Linux then? Your example assumes a .db file and probably default paths for running ArchiveBox on a Linux Desktop where the Firefox installation also resides?

Also, is there possibly any way to treat a history with a different level of care than separately passed pages? Like bookmarks I wanna frequently save new versions of, history I mostly care about saving once or maybe a few times per year. Reason is I wanna keep storage usage a bit in check as well as run times.

Sorry to break open an old issue, but this seems pretty relevant, happy to post in a separate issue if deemed necessary though. :) Thanks a lot for building this application by the way! <3

**Comment by pirate** [comment]
@GlassedSilver sorry I forgot to get back to this. If you still want help I recommend opening a new issue, happy to assist with making the bookmark transfer easy!
