### ISSUE TITLE
Configurable Output Directory

### ISSUE THREAD

**Issue by pigmonkey** [pirate/bookmark-archiver#94]
I want bookmark-archiver to place its output in a directory I specify, not the default `output/` directory in the repository. To do this I replaced the `OUTPUT_DIR` variable in `config.py` with a check for an environment variable and a fallback to the current default. This matches the rest of the configuration options and works great for me.

    OUTPUT_DIR = os.getenv('OUTPUT_DIR', os.path.join(REPO_DIR, 'output'))

I'm happy to submit a pull request with this, but I'm curious if there was some reason this was not already the default config. Does this break something I haven't considered?

**Comment by pirate** [comment]
I was originally intending on adding paid multi-user support which would include multiple custom output directories, (so people could host a federated collection of archives all managed together for their community), but given how little time I have these days I think it's about time to enable custom output folders and let people do it themselves.

Feel free to submit that PR and I'll accept it, otherwise I can add this line myself.
